### ISSUE TITLE
Installation of datashim results in an error

### ISSUE THREAD

**Issue by shlomitk1** [datashim-io/datashim#107]
I'm getting the following error while deploying datashim:
`error: unable to recognize "https://raw.githubusercontent.com/datashim-io/datashim/master/release-tools/manifests/dlf.yaml": no matches for kind "CSIDriver" in version "storage.k8s.io/v1"`
Earlier installations were successful. I suspect that https://github.com/datashim-io/datashim/pull/105 is the cause.

**Comment by YiannisGkoufas** [comment]
Hi @shlomitk1 can you post the output of `kubectl version` command? I think with #105 we broke compatibility with pre-1.18 kubernetes clusters.

**Comment by shlomitk1** [comment]
It was 1.16, after changing to 1.18 the problem has disappeared.
