### ISSUE TITLE
S3 bucket creation command is missing for archive handler

### ISSUE THREAD

**Issue by Tomcli** [datashim-io/datashim#113]
When running archive mode to load dataset into the S3 bucket, minio and other S3 server buckets are not created by the `aws s3 cp` command anymore. #112 is the quick fix for not breaking it, but ideally we should make the archive handle commands configurable when we need to make changes on how to pull the dataset.

**Comment by pkoutsov** [comment]
Since with #112 the archive handler is  working, would it be okay with you @Tomcli to close this issue and you could make a new one with a spec proposal of how to make the commands configurable for archives?

**Comment by srikumar003** [comment]
Closing this issue due to staleness
