### ISSUE TITLE
Using defaultStorage leads to error: duplication of volumes

### ISSUE THREAD

**Issue by MauroRibeiroHV** [datashim-io/datashim#115]
In the deployment of the backend there is a container and an initContainer, and both need the same storage. There is a block of code that defines the volumes in the container, but in the initContainer the same block of code is inside an if that validates the flag defaultStorage.enabled. So, with the flag set to false, we will have the volumeMounts configuration in the container and not in the iniContainer. Since to define the storage we need to configure the additionalVolumeMounts value with our volumes, in the container we would have duplicated entries.

The configuration of volumes of the backend deployment container lacks the if {{- if .Values.cvat.backend.defaultStorage.enabled }} like in the configuration of the volumes of the initContainer.

**Comment by pkoutsov** [comment]
Hi @MauroRibeiroHV , I am not quite sure where this ```{{- if .Values.cvat.backend.defaultStorage.enabled }}``` is missing from. Could you maybe open a PR about this issue since you kinda already figured out what is missing? 🙂

**Comment by MauroRibeiroHV** [comment]
Sorry, my mistake. This is an issue in another project, by mistake I created here.
