### ISSUE TITLE
Implement NooBaa caching plugin

### ISSUE THREAD

**Issue by pkoutsov** [datashim-io/datashim#121]
Implement an S3-to-S3 caching plugin, similar to the [already existing CEPH-based plugin](https://github.com/datashim-io/datashim/tree/master/plugins/ceph-cache-plugin), which is based on [NooBaa](https://github.com/noobaa/noobaa-core).

**Comment by srikumar003** [comment]
We have tested out Noobaa's cache implementation and run into a few issues (https://github.com/noobaa/noobaa-core/issues/6709). We'll revisit this when those issues have been resolved
