### ISSUE TITLE
No PVC was generated 

### ISSUE THREAD

**Issue by davidyuyuan** [datashim-io/datashim#125]
As documented in https://github.com/datashim-io/datashim/blob/master/docs/Archive-based-Datasets.md, a PVC should be generaed for an archive dataset. I ran "kubectl apply -f https://github.com/datashim-io/datashim/raw/master/examples/templates/example-archive.yaml". A dataset was created correctly. The corresponding PVC did not exist.

**Comment by pkoutsov** [comment]
Hello @davidyuyuan did you follow the instructions for archive-based dataset found [here](https://datashim-io.github.io/datashim/Archive-based-Datasets/)? I suspect that the example archive-based dataset you created results in no PVC created because the ```minio-conf``` secret is missing.

**Comment by srikumar003** [comment]
Closing this issue as the problem seems resolved
