### ISSUE TITLE
Support for dataset versioning?

### ISSUE THREAD

**Issue by enricorotundo** [datashim-io/datashim#126]
Hi all! Is there any plan for supporting dataset versioning?

**Comment by pkoutsov** [comment]
Hello @enricorotundo there are no immediate plans to support this. However, at this time point it could be nice to start working on a potential spec of this feature with some initial thoughts. Feel free to share in this issue any ideas you might have for this feature 🙂

**Comment by srikumar003** [comment]
Would be a very cool feature but is not currently planned
