### ISSUE TITLE
deprecation warning

### ISSUE THREAD

**Issue by masterkain** [datashim-io/datashim#129]
dlf/csi-attacher-nfsplugin-0

Warning: 299 - "storage.k8s.io/v1beta1 VolumeAttachment is deprecated in v1.19+, unavailable in v1.22+; use storage.k8s.io/v1 VolumeAttachment"

**Comment by pkoutsov** [comment]
Thanks for reporting this issue @masterkain. Indeed for k8s v1.22+ the attachers of nfs and h3 datasources have this issue.

**Comment by srikumar003** [comment]
Closing this issue as we have updated the sidecar dependencies. Hopefully, that makes this problem go away!
