### ISSUE TITLE
Could not mount a pvc to pod

### ISSUE THREAD

**Issue by virtyos** [datashim-io/datashim#130]
Getting error `MountVolume.MountDevice failed for volume "pvc-c3593f1f-d21e-4fcd-90f0-e4d73e554ff6" : kubernetes.io/csi: attacher.MountDevice failed to create newCsiDriverClient: driver name ch.ctrox.csi.s3-driver not found in the list of registered CSI drivers`

**Comment by virtyos** [comment]
Have resolved. ) 

I'm working on microk8s and it uses /var/snap/microk8s/common/var/lib/kubelet path, not var/lib/kubelet.
So I just downloaded your yaml file and replaced all paths in it with actual value

**Comment by srikumar003** [comment]
Thanks @virtyos I'll open an issue on automatically detecting the kubelet path during installation

**Comment by gdubya** [comment]
@srikumar003 did you create such an issue? We are seeing the same error for a Nutanix Karbon k8s cluster but i'm not sure how to verify whether or not the path is correct for our cluster.

**Comment by srikumar003** [comment]
@gdubya I have not created it yet but will do. To verify the paths, you will have to login to one of the nodes and look path to kubelet. I don't know a better method, tbh

**Comment by gdubya** [comment]
Thanks @srikumar003. In case anyone is looking for this in the future: it looks like Nutanix Karbon has a similar folder structure to IBM (`/var/data/kubelet`), at least in our case.

**Comment by gdubya** [comment]
It looks like the paths are not the problem in our case (the default paths using /var/lib/kubelet are correct). I'll create a new issue to avoid mixing with this one.
