### ISSUE TITLE
Transport endpoint is not connected

### ISSUE THREAD

**Issue by virtyos** [datashim-io/datashim#135]
Sometimes I got an error "transport endpoint is not connected" from my pods (csi-s3 volumes are mounted to them). I have to remount volumes and restart pods

**Comment by balapydi** [comment]
@YiannisGkoufas, I am facing this issue whenever I try to write anything on the mount.
I am using Dell ECS bucket.

**Comment by remidebette** [comment]
Hi, do you have any news on this?

**Comment by srikumar003** [comment]
This has been reported again in #153. As we have reported in that issue, solving this requires some changes to CSI-S3 and is pending investigation. Closing this issue to avoid duplication
