### ISSUE TITLE
[Question] Is Datashim still not ready for production?

### ISSUE THREAD

**Issue by MauroRibeiroHV** [datashim-io/datashim#144]
Hi
I see a comment from 2019 on datashim/src/csi-s3/README.md that says:

CSI for S3
This is a Container Storage Interface (CSI) for S3 (or S3 compatible) storage. This can dynamically allocate buckets and mount them via a fuse mount into any container.

Status
This is still very experimental and should not be used in any production environment. Unexpected data loss could occur depending on what mounter and S3 storage backend is being used.

Is this still true?
I saw a that the release was this year, do you guys still experience data loss?

Thanks

**Comment by srikumar003** [comment]
Closing this issue. Please reopen or start a discussion, if further investigation is needed.
