### ISSUE TITLE
ErrImagePull error for many PODs

### ISSUE THREAD

**Issue by swapnilmwagh** [datashim-io/datashim#147]
$ kubectl get all -n dlf
NAME                                    READY   STATUS              RESTARTS   AGE
pod/csi-attacher-nfsplugin-0            0/2     ErrImagePull        0          22m
pod/csi-attacher-s3-0                   0/1     ErrImagePull        0          22m
pod/csi-controller-h3-0                 0/3     ContainerCreating   0          22m
pod/csi-nodeplugin-h3-ljfbp             0/2     ErrImagePull        0          22m
pod/csi-nodeplugin-nfsplugin-npnh4      0/2     ErrImagePull        0          22m
pod/csi-provisioner-s3-0                0/1     ErrImagePull        0          22m
pod/csi-s3-pzjc7                        0/2     ErrImagePull        0          22m
pod/dataset-operator-644f75fcbb-mw8v2   0/1     Init:ErrImagePull   0          22m

Please check and suggest. Thanks

**Comment by fferrann** [comment]
Does your Kubernetes cluster have any networking issues? Are other pods affected (e.g. other images)? I can pull the images without a problem.

**Comment by srikumar003** [comment]
@swapnilmwagh hi, apologies for the late reply. Are you still facing this issue ? Please comment

**Comment by srikumar003** [comment]
Closing this issue as it has gone stale
