### ISSUE TITLE
minio/s3 Dataset x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by yingding** [datashim-io/datashim#176]
I tried to create a Dataset from a minio bucket, which is compatible to s3 with type `COS`.
Got an error:
```
    provision:
      info: 'failed to provision volume with StorageClass "csi-s3": rpc error: code
        = Unknown desc = failed to check if bucket <public_bucket> exists: Get
        https://<minio-host>:<port>/<public_bucket>/?location=:
        x509: certificate signed by unknown authority'
```
Is it possible to turn off the x509 CA certificate check for my local custom SSL certificate of the minio object store?

**Comment by srikumar003** [comment]
It doesn't seem possible as the `bucketExists` check does not have options to ignore self-signed CA certificate. Also, csi-s3 uses minio-go client to perform the actual check
