### ISSUE TITLE
Datashim S3 CSI driver won't work on IBM Fyre OCP 4.8

### ISSUE THREAD

**Issue by Tomcli** [datashim-io/datashim#188]
When running Datashim with S3 CSI driver on IBM Fyre OCP 4.8. Datashim can create the PVC with the appropriate storage class, but the S3 CSI driver is unable to bound the PVC storage to the S3 endpoint. We suspect there could be a S3 CSI driver configuration need to be update for the IBM Fyre OCP 4.8. However, we are not sure what feature gates or OCP configuration is needed in order to enable it on Fyre.

For comparison, we have Datashim working on IBM Cloud openshift 4.8 as expected. So it's most likely due to OCP feature gates and apiserver configuration between the two platform.

cc @ckadner @jbusche

**Comment by srikumar003** [comment]
Closing as there has been no followup since
