### ISSUE TITLE
How to handle multi-arch setup?

### ISSUE THREAD

**Issue by collinarnett** [datashim-io/datashim#191]
Currently images tags are labeled with their architecture. I have a cluster with a mix of arm64 and amd64 nodes. I'm not sure with how to handle this setup with the way the datashim manifests are currently.

**Comment by srikumar003** [comment]
@collinarnett we have an ongoing issue about this (#187) and working on improving our CI pipeline to push multi-arch-images.

**Comment by srikumar003** [comment]
@collinarnett We now have new charts that provide multi-arch images. Please check them out and let us know

**Comment by collinarnett** [comment]
> @collinarnett We now have new charts that provide multi-arch images. Please check them out and let us know

Thanks so much. I have tried out the images minus the chart and they work as expected :smile:
