### ISSUE TITLE
Bug on dataset operator eviction

### ISSUE THREAD

**Issue by christian-pinto** [datashim-io/datashim#20]
If the dataset operator pod gets evicted for some reason a new instance is started. However, the evicted instance seems to be holding a lock causing a deadlock.

In the new operator instance logs you can only see the following line repeated indefinitely:
```{"level":"info","ts":1589796411.546784,"logger":"leader","msg":"Not the leader. Waiting."}```
The pod is not capable of continuing its execution.

This seems to be an issue with the operator-framework that is being triaged at the below link:
https://github.com/operator-framework/operator-sdk/issues/1305

**Comment by srikumar003** [comment]
This has been fixed and issue is no longer valid
