### ISSUE TITLE
mounting a folder in s3

### ISSUE THREAD

**Issue by nik-afa** [datashim-io/datashim#200]
Hello, thank you for your product, I have a question, is it possible to mount not the entire bucket, but only its specific folder when mounting an s3 bucket? 
For example, do not mount 
`https://my-bucket.s3.amazonaws.com/`
instead mount like this
`https://my-bucket.s3.amazonaws.com/folder`

**Comment by srikumar003** [comment]
at this moment, Datashim's CSI-S3 implementation does not support accessing prefixes for S3 buckets (i.e. folders). The entire bucket is mounted but you can chose to read/write to a specific subfolder. 

However, we are open to patches :-)

**Comment by vshinde727** [comment]
Hi - This really seems very useful feature, is there any plan for a new version with above changes?

**Comment by srikumar003** [comment]
We have a PR open for this feature: #263
