### ISSUE TITLE
Pod "csi-controller-h3-0" not working on k8s 1.22

### ISSUE THREAD

**Issue by wongan4** [datashim-io/datashim#206]
I found pod "csi-controller-h3-0" will fail on k8s 1.22, but can still mount s3 volume. Can I know is there any suggestion?

I guess should be this container "csi-cluster-driver-registrar" error.

csi-cluster-driver-registrar:
    Port:          <none>
    Host Port:     <none>
    Args:
      --v=5
      --pod-info-mount-version="v1"
      --csi-address=$(ADDRESS)
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated

log:
I1013 08:01:35.349862       1 main.go:77] Version: v1.0.1-0-g0660c6c6
I1013 08:01:35.349984       1 main.go:80] Attempting to open a gRPC connection with: "/csi/csi.sock"
I1013 08:01:35.349996       1 connection.go:69] Connecting to /csi/csi.sock
I1013 08:01:35.350285       1 connection.go:96] Still trying, connection is CONNECTING
I1013 08:01:35.350575       1 connection.go:93] Connected
I1013 08:01:35.350593       1 main.go:88] Calling CSI driver to discover driver name.
I1013 08:01:35.350657       1 connection.go:137] GRPC call: /csi.v1.Identity/GetPluginInfo
I1013 08:01:35.350666       1 connection.go:138] GRPC request: {}
I1013 08:01:35.352065       1 connection.go:140] GRPC response: {"name":"csi-h3","vendor_version":"v1.1.0"}
I1013 08:01:35.352519       1 connection.go:141] GRPC error: <nil>
I1013 08:01:35.352526       1 main.go:96] CSI driver name: "csi-h3"
I1013 08:01:35.352531       1 main.go:100] Loading kubeconfig.
I1013 08:01:35.353143       1 k8s_register.go:54] AttachRequired: true
I1013 08:01:35.353162       1 k8s_register.go:55] PodInfoOnMountVersion: "v1"
I1013 08:01:35.353167       1 k8s_register.go:58] Registering csidrivers
E1013 08:01:35.362114       1 k8s_register.go:71] the server could not find the requested resource

**Comment by srikumar003** [comment]
@wongan4 The CSI plugins supported by Datashim are treated independently.  S3 buckets are handled by CSI-S3. H3 was an experimental storage system that Datashim supported last year. 

You can install Datashim without CSI-H3 by modifying the Helm values file: [See this comment](https://github.com/datashim-io/datashim/issues/132#issuecomment-1120471474)
