### ISSUE TITLE
question: readonly parameter

### ISSUE THREAD

**Issue by vsoch** [datashim-io/datashim#212]
Hiya! Could you point me to documentation about the details for the readonly true/false parameter? E.g., what are the limitations, implementation under the hood, number of pods you've tested, etc.  This might be good to go under FAQ (directly or as a link) because I went looking for it there. Thank you!

**Comment by srikumar003** [comment]
@vsoch Its right, there is no documentation for this parameter. This is only implemented for mounting object storage (s3) buckets, if you use `goofys` or `s3fs` mounters. If `readonly` is set, then an additional parameter (`ro`) is passed to the mounter at the time the volume is bound to the pod. 

A limitation here is that a process running in the pod containers (unless the pod spec has the volume specified with access mode `ReadOnlyMany`)  may not be necessarily aware of this, so there is a possibility of an error when it tries to write a file to a `read only` volume. 

IIRC, we have used the readonly parameter for a study on genome analysis using Kubeflow reported here: https://link.springer.com/chapter/10.1007/978-3-030-90539-2_28.

**Comment by srikumar003** [comment]
Linked issues to the main README so that users can search for answered questions. FAQ will be revisited at a later point in time.
