### ISSUE TITLE
`monitor-pods-datasets` does not seem working.

### ISSUE THREAD

**Issue by Magicloud** [datashim-io/datashim#248]
Following the sample in README, `Dataset` creation worked fine. I saw the PV and mounted it into pod successfully. But I could not get the `metadata.labels.dataset` labels working. There were just nothing in `/mnt`.

**Comment by srikumar003** [comment]
@Magicloud does the namespace you are using show up in the output of:
`kubectl get ns -l monitor-pods-datasets=enabled`

**Comment by Magicloud** [comment]
@srikumar003 Yes, it is the default namespace.

**Comment by srikumar003** [comment]
It might be that you have run into the certificate expiry issue that was reported (and solved) in #225

To verify, check if there is any output for the following command that relates to the webhook:
`kubectl logs <dataset-operator-pod-name> -c dataset-operator -n dlf | grep -i ERROR`

We have fixed this in #230 and a new image has been rolled out with the fix. You would either have to reinstall Datashim or , to reduce disruption:
1. Check if the `imagePullPolicy` for the operator has been set to `Always`:
`kubectl get deployment dataset-operator -n dlf -oyaml |grep -i imagePullPolicy`
If not, do `kubectl edit deployment dataset-operator -n dlf` and make the change
2. Scale down the deployment and scale it back up to force restart of the operator:
` kubectl scale deployment dataset-operator -n dlf --replicas=0`
`kubectl scale deployment dataset-operator -n dlf --replicas=1`

**Comment by Magicloud** [comment]
This is the output:
```
1.6807863583197076e+09	ERROR	controller-runtime.certwatcher	error re-reading certificate	{"error": "tls: failed to find any PEM data in certificate input"}
1.6807863583200142e+09	ERROR	controller-runtime.certwatcher	error re-reading certificate	{"error": "tls: failed to find any PEM data in certificate input"}
```

Updated the image. But seems like it is conflict with our weavenet usage. I got `Error from server (InternalError): error when creating "s3-test.yml": Internal error occurred: failed calling webhook "mpod.datashim.io": failed to call webhook: Post "https://webhook-server.dlf.svc:443/mutate-v1-pod?timeout=10s": Address is not allowed`. Will need to try it on host network mode.

Also, what does the scientific notation in the first column mean?

**Comment by srikumar003** [comment]
So it is the certificate expiry issue as I mentioned earlier. The first column is the timestamp for the log entry

**Comment by Magicloud** [comment]
OK. Confirmed all worked fine. Thanks.
