### ISSUE TITLE
When DataSet is deleted, associated PV and PVCs remain

### ISSUE THREAD

**Issue by starpit** [datashim-io/datashim#261]
Perhaps these should utilize [`ownerReferences`](https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/), so that kubernetes can GC the PV and PVC when the DataSet goes away?

**Comment by srikumar003** [comment]
@starpit this should be done automatically. Was the PVC bound to any pod ? if that is the case, then the Dataset object gets deleted but the corresponding `DatasetInternal` object still has a reference to the PVC and will not be deleted. When the pod is deleted, the PVC is unbound and all the associated objected will get GC-ed. 

Please post here the `kubectl describe` logs for any PVC/PV/Dataset/DatasetInternal that is still remaining

**Comment by starpit** [comment]
i was probably mistaken. closing
