### ISSUE TITLE
Is it possible to mount postgres volume in space?

### ISSUE THREAD

**Issue by CelioVTeixeira** [datashim-io/datashim#279]
Is it possible to mount postgres volume in space?

could someone help me with this:

<img width="740" alt="Code2" src="https://github.com/datashim-io/datashim/assets/84182592/7d886266-fef9-4746-aa66-47711240dae2">

Output:
<img width="959" alt="image" src="https://github.com/datashim-io/datashim/assets/84182592/594efe5b-e9ba-42ad-96f4-e981a5880ff7">

chmod: changing permissions of '/var/lib/postgresql/data': Operation not permitted 2023-07-19T13:20:31.062438835Z The files belonging to this database system will be owned by user "postgres". 2023-07-19T13:20:31.062519442Z This user must also own the server process. 2023-07-19T13:20:31.062530644Z 2023-07-19T13:20:31.062536366Z The database cluster will be initialized with locale "en_US.utf8". 2023-07-19T13:20:31.062543682Z The default database encoding has accordingly been set to "UTF8". 2023-07-19T13:20:31.062548451Z The default text search configuration will be set to "english". 2023-07-19T13:20:31.062572944Z 2023-07-19T13:20:31.062578018Z Data page checksums are disabled. 2023-07-19T13:20:31.062592916Z 2023-07-19T13:20:31.081540211Z initdb: error: could not change permissions of directory "/var/lib/postgresql/data": Operation not permitted 2023-07-19T13:20:31.083994705Z fixing permissions on existing directory /var/lib/postgresql/data ...

could someone help me with this please

**Comment by srikumar003** [comment]
@CelioVTeixeira Looks like a problem with Postgres configuration, rather than a Datashim/S3 issue. In general, it is not a good idea to use a S3 bucket or even a remote FS as the storage backend for Postgres. 

Closing this issue unless there is an error emanating from Datashim (please add a comment)
