### ISSUE TITLE
PersistentVolumeClaims is in pending state

### ISSUE THREAD

**Issue by sandeepsingh2023** [datashim-io/datashim#302]
Hi,
I am using below code to test this.
After applying the yml my pvc is geeting in pending state

---
apiVersion: com.ie.ibm.hpsys/v1alpha1
kind: Dataset
metadata:
  name: example-dataset
spec:
  local:
    type: "COS"
    accessKeyID: "*****"
    secretAccessKey: "******"
    endpoint: "https://s3.eu-central-2.wasabisys.com"
    bucket: "dbdumps"

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: example
    dataset.0.id: "example-dataset"
    dataset.0.useas: "mount"
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: "example-dataset"
  volumes:
  - name: "example-dataset"
    persistentVolumeClaim:
      claimName: "example-dataset"
---
apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  type: LoadBalancer
  selector:
    app: example
  ports:
  - port: 80
    targetPort: 80
    
  Can anyone help me with this?

**Comment by srikumar003** [comment]
@sandeepsingh2023 Please look in the logs of `csi-s3` and `csi-provisioner` containers to see if there are any errors. You can post the errors and warnings here for us to take a look

**Comment by sandeepsingh2023** [comment]
> @sandeepsingh2023 Please look in the logs of `csi-s3` and `csi-provisioner` containers to see if there are any errors. You can post the errors and warnings here for us to take a look

@srikumar003 I am getting this error while creating the pod:-

0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims. preemption: 0/3 nodes are available: 3 Preemption is not helpful for scheduling.

and Below logs when i describe my pvc:-

> kubectl describe pvc example-dataset
Name:          example-dataset
Namespace:     default
StorageClass:  csi-s3
Status:        Pending
Volume:        
Labels:        dataset=example-dataset
Annotations:   volume.beta.kubernetes.io/storage-provisioner: ch.ctrox.csi.s3-driver
               volume.kubernetes.io/storage-provisioner: ch.ctrox.csi.s3-driver
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Used By:       nginx
Events:
  Type    Reason                Age                    From                                                                              Message
  ----    ------                ----                   ----                                                                              -------
  Normal  ExternalProvisioning  3m12s (x2384 over 9h)  persistentvolume-controller                                                       waiting for a volume to be created, either by external provisioner "ch.ctrox.csi.s3-driver" or manually created by system administrator
  Normal  Provisioning          2m50s (x167 over 9h)   ch.ctrox.csi.s3-driver_csi-provisioner-s3-0_4b45167e-3781-4532-8072-d023a86768e9  External provisioner is provisioning volume for claim "default/example-dataset"

**Comment by srikumar003** [comment]
@sandeepsingh2023 so it seems CSI-S3 was not able to provision the volume due to some reason. Can you find out from the logs of csi-s3, like so:
`kubectl logs -n dlf <csi-s3-pod-name> -c csi-s3`
