### ISSUE TITLE
Decouple PVC from Dataset

### ISSUE THREAD

**Issue by udbhav-hbk** [datashim-io/datashim#321]
Currently as soon as we deploy the "Dataset" object, a PVC and ConfigMap gets created. Instead of this, we would like to create PVC separately which uses csi-s3 storageClass and avoid creation of PVC dynamically through Dataset.

Is this supported? If so, how can we do that?

**Comment by srikumar003** [comment]
@udbhav-hbk Am I correct in understanding that you are trying to use CSI-S3 on its own without needing Dataset objects ? This is possible. You can use CSI-S3 as a standalone service. See https://github.com/ctrox/csi-s3 for how to achieve that

**Comment by srikumar003** [comment]
closing this question as it seems to be resolved. Please reopen if needed
