### ISSUE TITLE
Port Requirements for S3

### ISSUE THREAD

**Issue by jkeerthi-hbk** [datashim-io/datashim#323]
We are using the dlf.yaml manifest for S3 integration for our usecase. We could see certain ports required by services in the manifest - 9443, 443 and 12345.
Are these the required ports to be opened for S3 integration?

**Comment by srikumar003** [comment]
@jkeerthi-hbk 12345 is a random port that we chose for CSI-S3 attacher service but the actual communication happens through RPC. 443 and 9443 are the ports for the webhook service that mutates the pods with the dataset labels.

**Comment by jkeerthi-hbk** [comment]
@srikumar003 Got it. For an airgapped VM that uses datashim to connect to an S3 bucket, the only port that needs to be opened on the VM is 443?

**Comment by srikumar003** [comment]
I am not sure I understand your network topology but 443 is required if you are using dataset labels in your pods

Connecting to S3 is an outbound operation from the K8s cluster, so it does not require any ports to be opened

**Comment by srikumar003** [comment]
Closing this issue as it seems to be resolved. Please open again if you have more information
