### ISSUE TITLE
tls: failed to find any PEM data in certificate input

### ISSUE THREAD

**Issue by davidyuyuan** [datashim-io/datashim#325]
dataset-operator creshes in Minikube v1.32.0 (Kubernetes 1.28.3) due to the mismatch of the certificate formats. The same issue was encountered in Kubernetes 1.28.2 running in Docker Desktop, too. Here is the log message in crashing pod "kubectl logs po/dataset-operator-8697cb49c6-z2ln5 -n dlf":

Defaulted container "dataset-operator" out of: dataset-operator, generate-keys (init)
1.7028426980553865e+09  INFO    controller-runtime.metrics      Metrics server is starting to listen  {"addr": ":8080"}
1.7028426980554967e+09  INFO    dataset-operator-setup  Operator Version: 0.3.0-alpha
1.702842698055504e+09   INFO    dataset-operator-setup  Go Version: go1.19.13
1.7028426980555058e+09  INFO    dataset-operator-setup  Go OS/Arch: linux/arm64
1.7028426980555067e+09  INFO    dataset-operator-setup  initialised manager
1.7028426980556464e+09  INFO    dataset-operator-setup  Server set up as well!
1.7028426980556524e+09  INFO    dataset-operator-setup  Setting up webhooks
1.7028426980556564e+09  INFO    dataset-operator-setup  Registering mutating webhook
1.7028426980556867e+09  INFO    controller-runtime.webhook      Registering webhook     {"path": "/mutate-v1-pod"}
1.7028426980557103e+09  INFO    dataset-operator-setup  starting manager
1.7028426980558805e+09  INFO    controller-runtime.webhook.webhooks     Starting webhook server
1.7028426980559332e+09  INFO    Starting server {"path": "/metrics", "kind": "metrics", "addr": "[::]:8080"}
1.7028426980559785e+09  INFO    Starting server {"kind": "health probe", "addr": "[::]:8081"}
1.7028426980559928e+09  INFO    Stopping and waiting for non leader election runnables
1.7028426980560012e+09  INFO    Stopping and waiting for leader election runnables
1.7028426980560453e+09  INFO    controller.dataset      Starting EventSource    {"reconciler group": "com.ie.ibm.hpsys", "reconciler kind": "Dataset", "source": "kind source: *v1alpha1.Dataset"}
1.7028426980560615e+09  INFO    controller.dataset      Starting Controller     {"reconciler group": "com.ie.ibm.hpsys", "reconciler kind": "Dataset"}
1.7028426980560813e+09  INFO    controller.datasetinternal      Starting EventSource    {"reconciler group": "com.ie.ibm.hpsys", "reconciler kind": "DatasetInternal", "source": "kind source: *v1alpha1.DatasetInternal"}
1.7028426980560913e+09  INFO    controller.datasetinternal      Starting Controller     {"reconciler group": "com.ie.ibm.hpsys", "reconciler kind": "DatasetInternal"}
1.702842698056109e+09   ERROR   controller.datasetinternal      Could not wait for Cache to sync      {"reconciler group": "com.ie.ibm.hpsys", "reconciler kind": "DatasetInternal", "error": "failed to wait for datasetinternal caches to sync: timed out waiting for cache to be synced"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:208
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:234
sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func1
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/manager/runnable_group.go:218
1.7028426980561357e+09  ERROR   error received after stop sequence was engaged  {"error": "failed to wait for datasetinternal caches to sync: timed out waiting for cache to be synced"}
sigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).engageStopProcedure.func1
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/manager/internal.go:541
1.7028426980561068e+09  ERROR   controller.dataset      Could not wait for Cache to sync        {"reconciler group": "com.ie.ibm.hpsys", "reconciler kind": "Dataset", "error": "failed to wait for dataset caches to sync: timed out waiting for cache to be synced"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:208
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:234
sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func1
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/manager/runnable_group.go:218
1.7028426980561485e+09  INFO    Stopping and waiting for caches
1.7028426980561671e+09  INFO    Stopping and waiting for webhooks
1.7028426980561764e+09  INFO    Wait completed, proceeding to shutdown the manager
1.7028426980561793e+09  ERROR   dataset-operator-setup  problem running manager {"error": "tls: failed to find any PEM data in certificate input"}
main.main
        /dataset-operator/main.go:140
runtime.main
        /usr/local/go/src/runtime/proc.go:250
1.70284269805616e+09    ERROR   error received after stop sequence was engaged  {"error": "failed to wait for dataset caches to sync: timed out waiting for cache to be synced"}
sigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).engageStopProcedure.func1
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/manager/internal.go:541

**Comment by davidyuyuan** [comment]
FYI. The deployment onto Kubernetes v1.27.3-gke.100 works.

**Comment by davidyuyuan** [comment]
The dataset-operator works in Minikube v1.32.0 (Kubernetes 1.28.3) on another MacBook. Not sure why. Canceling the issue.

**Comment by maksimsamt** [comment]
The same error on k8s 1.32.6, installing by Helm chart
```
I0801 19:53:23.179030   62274 warnings.go:110] "Warning: tls: failed to find any PEM data in certificate input"
```
