### ISSUE TITLE
Missing affinity options for helm charts

### ISSUE THREAD

**Issue by muandane** [datashim-io/datashim#329]
I'm using datashim to connect to minio s3 bucket with access key and secret on AKS cluster with linux and windows nodes. due to missing affinity configuration on the Daemonsets for csi-nfs-chart & csi-s3-chart they attach to the windows node and fail to deploy.

is it possible for me to add PR to address this issue ?

**Comment by srikumar003** [comment]
@muandane that would be very welcome! Please link the PR to this issue

**Comment by muandane** [comment]
@srikumar003 Done i added the affinity option and tested it globally
