### ISSUE TITLE
ci: Update testing action to wait for Dataset operator to be ready

### ISSUE THREAD

**Issue by srikumar003** [datashim-io/datashim#347]
The test with Kind action (.github/workflows/testing.yml) currently assumes that Datashim installation proceeds without failure. 
To do:
- [x] this should be updated with a `kubectl wait` condition to check that the Dataset operator is up and running

**Comment by AlessandroPomponio** [comment]
What we could do is add a wait for the Dataset operator before the creation of the Dataset in the testing CI. Something like:

```commandline
kubectl wait --for=condition=ready -n dlf pod -l name=dataset-operator --timeout=2m || (kubectl get all -n dlf && exit 1)
```

**Comment by srikumar003** [comment]
Fixed in commit https://github.com/srikumar003/datashim/commit/a37f996e34434b2af3fb70fab39e04d241752a78
