### ISSUE TITLE
Bug: pod for downloading archive datasets does not support arm64 architecture

### ISSUE THREAD

**Issue by AlessandroPomponio** [datashim-io/datashim#367]
**What happened**: After creating a dataset of type `ARCHIVE`, I see no content in the pod that mounts the dataset. This is because the download pod fails with 

```
exec /bin/sh: exec format error
```

**What you expected to happen**: everything should work

**How to reproduce it (as minimally and precisely as possible)**: 
1. Run 
    ```bash
    kubectl apply -n dlf -f https://github.com/AlessandroPomponio/datashim/blob/ap_365_readme_updates/examples/minio/minio.yaml
    ```
2. Run
    ```bash
    cat <<EOF | kubectl apply -f -
    apiVersion: v1
    kind: Pod
    metadata:
      name: nginx
      labels:
        dataset.0.id: "archive-dataset"
        dataset.0.useas: "mount"
    spec:
      containers:
        - name: nginx
          image: nginx
    EOF
    ```
3. Run 
    ```bash
    kubectl exec nginx -- ls mnt/datasets/archive-dataset/
    ```

**Anything else we need to know?**:

**Environment**:
- Datashim version:0.4.0 
- Kubernetes version (use `kubectl version`):
- Kubernetes distribution: 
        ```
        Client Version: v1.30.0
        Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
        Server Version: v1.30.0
        ```
- Cloud provider or hardware configuration: Macbook M1, using KIND
- Install tools: helm

**Comment by srikumar003** [comment]
The function here: https://github.com/datashim-io/datashim/blob/da435c8e470cdbfb61a5772efbc9c97cf4586698/src/dataset-operator/controllers/archive_handler.go#L14 
references a docker image that is not built with multi-arch support. The Dockerfile for that image is here: https://github.com/datashim-io/datashim/blob/da435c8e470cdbfb61a5772efbc9c97cf4586698/src/cos-uploader/Dockerfile#L2 

To fix this issue:
- [ ] Update the image building scripts to include the docker image for archive
- [ ] Upload the archive docker image to quay.io/datashim-io

**Comment by AlessandroPomponio** [comment]
Everything seems to have worked https://github.com/datashim-io/datashim/actions/runs/10167107008/job/28122136358
cc @srikumar003

**Comment by srikumar003** [comment]
Closing this issue
