### ISSUE TITLE
Bug: Helm registry broken

### ISSUE THREAD

**Issue by matias-easymile** [datashim-io/datashim#374]
**What happened**:
https://github.com/datashim-io/datashim/commit/e219c310a957c8716b6ff0aa83da5b6ab7ed76ea
Since this commit, it seems the index.yaml file is not deployed on helm repository url :
```
Error: looks like "https://datashim-io.github.io/datashim/" is not a valid chart repository or cannot be reached: failed to fetch https://datashim-io.github.io/datashim/index.yaml : 404 Not Found
``` 

**What you expected to happen**:
Helm repo fetch is working as expected.

**How to reproduce it (as minimally and precisely as possible)**:
```
$ helm repo add datashim https://datashim-io.github.io/datashim/
$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "datashim" chart repository (https://datashim-io.github.io/datashim/):
	failed to fetch https://datashim-io.github.io/datashim/index.yaml : 404 Not Found
``` 

**Anything else we need to know?**:

**Environment**:
- Datashim version: NA
- Kubernetes version (use `kubectl version`): NA
- Kubernetes distribution: NA
- Cloud provider or hardware configuration: NA
- OS (e.g: `cat /etc/os-release`): NA
- Kernel (e.g. `uname -a`): NA
- Install tools: NA
- Others: NA

**Comment by matias-easymile** [comment]
@AlessandroPomponio

**Comment by AlessandroPomponio** [comment]
Thank you very much for reporting this @matias-easymile !

@srikumar003 when we use `pipenv run mkdocs gh-deploy` in the website's CI, we end up losing the yaml that allows helm installation (https://github.com/datashim-io/datashim/blob/520a50c7e1c08b1a15772eb3f2ea5f1d9c51639c/index.yaml)

Do we have a recipe to create this file programmatically or do we need to copy this file all the time?

**Comment by matias-easymile** [comment]
Great to know the issue is confirmed.
And seems already fixed, thanks for your lightspeed correction 👍  

Have a nice day @AlessandroPomponio

**Comment by srikumar003** [comment]
@matias-easymile not completely fixed yet :-) We have a PR for the ci change that caused this in the first place and checking that it does not break anything

**Comment by srikumar003** [comment]
All good now
