### ISSUE TITLE
Fix goofys disconnection in case of error

### ISSUE THREAD

**Issue by viktoriaas** [datashim-io/datashim#76]
Hi, 
goofys needs syslog if fatal event happens. Installing package `netcat-openbsd` and running `nc -k -l -U /var/run/syslog &` fixes the issue and enpoint will not disconnect. I think this image `quay.io/k8scsi/csi-node-driver-registrar:v1.2.0` needs the fix. ([source](https://github.com/elliotchance/c2go/issues/674))

**Comment by YiannisGkoufas** [comment]
Hi @viktoriaas ! So it's an issue of `v1.2.0` version of `quay.io/k8scsi/csi-node-driver-registrar` ?

**Comment by viktoriaas** [comment]
Yes, this one is used in csi-s3 daemonset

**Comment by pkoutsov** [comment]
@viktoriaas from what I can tell from the description the necessary changes for this issue need to take place inside ```quay.io/k8scsi/csi-node-driver-registrar``` which is kinda out of our jurisdiction 🙂  If my understanding is correct I will close this issue

**Comment by viktoriaas** [comment]
@pkoutsov I'm closing the issue as it's old and I don't use datashim anymore :)

**Comment by pkoutsov** [comment]
@viktoriaas sorry to hear that you are not using datashim anymore, but out of curiosity, could you share with me with what you replaced datashim? 🙂

**Comment by viktoriaas** [comment]
@pkoutsov 
Datashim had many problems for our use case and needs. Some time ago  (at least 4 months imho) I sent an email to @YiannisGkoufas describing issues and possible improvements, but more like brainstorming and sharing ideas. We really needed working drivers so we ended up with:
- `democratic-csi` for NFS [(github link)](https://github.com/democratic-csi/democratic-csi)
-  for ceph rbd helm chart `ceph-csi/ceph-csi-rbd` [(link)](https://artifacthub.io/packages/helm/ceph-csi/ceph-csi-rbd)
- for sshfs `csi-sshfs` [(link)](https://github.com/chr-fritz/csi-sshfs)  which is old and not reliable but we need the functionality (we'd like to change this to samba also provided by `democratic-csi` but we face a couple of internal problems)
