### ISSUE TITLE
Node-driver-registrar not working after reboot

### ISSUE THREAD

**Issue by viktoriaas** [datashim-io/datashim#83]
Hi, 
I would like if [container node-driver-registrar in daemonset  csi-nodeplugin-nfsplugin ](https://github.com/IBM/dataset-lifecycle-framework/blob/master/src/csi-driver-nfs/chart/templates/csi-nodeplugin-nfsplugin.yaml) is expected to fail and not restart after some node problem. If a node reboots, the container node-driver-registrar stops working with log

```
I0202 01:11:30.758475       1 node_register.go:58] Starting Registration Server at: /registration/nfs.csi.k8s.io-reg.sock
I0202 01:11:30.758743       1 node_register.go:67] Registration Server started at: /registration/nfs.csi.k8s.io-reg.sock
I0202 01:11:31.425742       1 main.go:77] Received GetInfo call: &InfoRequest{}
I0202 01:11:54.363628       1 main.go:87] Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:true,Error:,}
E0202 14:07:00.314932       1 connection.go:129] Lost connection to unix:///plugin/csi.sock.
```

I've found out when I created job which had to mount some PVC with `csi-nfs` storageclass and it did not schedule on the node which was rebooted yesterday. Logs from the job:

```
Warning  FailedMount  51s                  kubelet            Unable to attach or mount volumes: unmounted volumes=[dest-volume], unattached volumes=[dest-volume default-token-9btxt]: timed out waiting for the condition
  Warning  FailedMount  45s (x9 over 2m53s)  kubelet            MountVolume.MountDevice failed for volume "pvc-bd3d6316-0342-45f0-981d-0cdc9ca165c3" : kubernetes.io/csi: attacher.MountDevice failed to create newCsiDriverClient: driver name nfs.csi.k8s.io not found in the list of registered CSI drivers
```
Shouldn't it be somehow periodically ensured that the daemon is alive? I can create a cronjob or something for my cluster but thought I will ask first.

**Comment by pkoutsov** [comment]
Hi @viktoriaas, I can understand the behavior you describe but this is not a datashim-related issue, but how the ```csi-nfs``` works in case of some node problem, right?

**Comment by viktoriaas** [comment]
@pkoutsov 
I don't know whether it's a `csi-nfs` plugin behaviour or it could be improved in datashim.  But again, the issue is old and not relevant anymore :) so closing
