### ISSUE TITLE
Creating a dataset from s3 bucket with 1GB of data results in ~9000 GB PVC

### ISSUE THREAD

**Issue by olevski** [datashim-io/datashim#87]
Hello and thank you for this really cool project.

I am trying to create a dataset on a k8s cluster that is hosted on an open stack provider. And it seems that every time I create a dataset I get a pvc and pv that are very large (9314 Gi) even though the S3 bucket I am using only has dummy data that is less than 1 GB in total.

```
NAME                  STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
example-dataset-gcs   Bound    pvc-85d52fa7-ab1e-4a4a-abb9-2ab687455188   9314Gi     RWX            csi-s3         22m
```

I thought this was happening because I was using open stack s3 compatible storage. However the same thing occurred when using gcs (which is also supposed to be s3 compatible). I apologize I could not try AWS s3 out because I do not have easy access to an account.

**Is there a way to specify how big the PV/PVC can be?** 

This is my only issue. Everything else seems to work.

I followed the templates here for creating the dataset:
https://github.com/IBM/dataset-lifecycle-framework/blob/master/examples/templates/example-dataset-s3-secrets.yaml
https://github.com/IBM/dataset-lifecycle-framework/blob/master/examples/templates/example-s3-secret.yaml

I installed using this command:
```
kubectl apply -f https://raw.githubusercontent.com/IBM/dataset-lifecycle-framework/master/release-tools/manifests/dlf.yaml
```

For this I am using kubernetes 1.19.6 on a rke cluster deployed on an openstack provider.

**Comment by YiannisGkoufas** [comment]
Hi @olevski, thanks for your interest and glad you find it useful!
The value that we set is indeed dummy because we don't have knowledge (and I am not sure if we can discover) the capacity of your bucket in the Object Store.
Just to clarify, this PVC doesn't take up any space on your cluster's storage since it's just mounting a remote bucket.
