### ISSUE TITLE
S3 config format

### ISSUE THREAD

**Issue by HelenCousins** [datashim-io/datashim#90]
I am trying to set this up with an S3 bucket.  I have provided my keys.  I get:

  | failed to provision volume with StorageClass "csi-s3": rpc  error: code = Unknown desc = failed to initialize S3 client: Endpoint:   does not follow ip address or domain name standards.
-- | --

I have:

endpoint=s3.eu-west-2.amazonaws.com

which is clearly wrong, but what would be RIGHT?

**Comment by YiannisGkoufas** [comment]
Hi @HelenCousins , apologies that this part is not very clear in the documentation.
The endpoint you provided, should be like this:

https://s3.eu-west-2.amazonaws.com or http://s3.eu-west-2.amazonaws.com

**Comment by HelenCousins** [comment]
well, now it isn't throwing errors but it is endlessly pending with no reason given.  I know I have the right credentials, as I can use them with rclone...

**Comment by YiannisGkoufas** [comment]
Hi @HelenCousins is `kubectl describe dataset/<YOUR_DATASET>` giving anything useful output?
Also would you mind sharing the Dataset spec without your credentials?

**Comment by HelenCousins** [comment]
apiVersion: com.ie.ibm.hpsys/v1alpha1
kind: Dataset
metadata:
  name: example-dataset2
spec:
  local:
    type: "COS"
    accessKeyID: "SECRET"
    secretAccessKey: "SECRET"
    endpoint: "s3.eu-west-2.amazonaws.com"
    bucket: "atestbuckethc7"
    region;


 kubectl describe datasets example-dataset2 
Name:         example-dataset2
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  com.ie.ibm.hpsys/v1alpha1
Kind:         Dataset
Metadata:
  Creation Timestamp:  2021-03-19T14:34:47Z
  Generation:          6
  Managed Fields:
    API Version:  com.ie.ibm.hpsys/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:caching:
          .:
          f:info:
          f:status:
        f:provision:
          .:
          f:status:
    Manager:      dataset-operator
    Operation:    Update
    Time:         2021-03-19T14:34:52Z
    API Version:  com.ie.ibm.hpsys/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:local:
          .:
          f:accessKeyID:
          f:bucket:
          f:endpoint:
          f:region:
          f:secretAccessKey:
          f:type:
    Manager:         kubectl-client-side-apply
    Operation:       Update
    Time:            2021-03-19T15:13:30Z
  Resource Version:  9020433
  Self Link:         /apis/com.ie.ibm.hpsys/v1alpha1/namespaces/default/datasets/example-dataset2
  UID:               07cb2b92-dadc-453f-bb1c-900792ec150a
Spec:
  Local:
    Access Key ID:      SECRET
    Bucket:             atestbuckethc7
    Endpoint:           http://s3.eu-west-2.amazonaws.com
    Region:             eu-west-2
    Secret Access Key:  SECRET
    Type:               COS
Status:
  Caching:
    Info:    No DLF caching plugins are installed
    Status:  Disabled
  Provision:
    Status:  Pending
Events:      <none>

**Comment by YiannisGkoufas** [comment]
Thanks @HelenCousins can you try instead the following:

```
apiVersion: com.ie.ibm.hpsys/v1alpha1
kind: Dataset
metadata:
  name: example-dataset2
spec:
  local:
    type: "COS"
    accessKeyID: "XXXXXXXXXXXXXXX"
    secretAccessKey: "XXXXXXXXXXX"
    endpoint: "https://s3.amazonaws.com"
    bucket: "atestbuckethc7"
    region: "eu-west-2"
```
Also, does is `atestbuckethc7` an existing bucket?

**Comment by HelenCousins** [comment]
it is a bucket, it contains junk, but ... existing junk

**Comment by YiannisGkoufas** [comment]
Haha okay! can you try the spec I suggested above? basically I think you need to use `endpoint=https://s3.amazonaws.com` and `region=eu-west-2`

**Comment by YiannisGkoufas** [comment]
Okay :( can you paste the output of this command: `kubectl get pods -n dlf` ?

**Comment by HelenCousins** [comment]
NAME                                READY   STATUS    RESTARTS   AGE
csi-attacher-nfsplugin-0            2/2     Running   0          6d4h
csi-attacher-s3-0                   1/1     Running   0          6d4h
csi-nodeplugin-nfsplugin-h8h2h      2/2     Running   0          6d4h
csi-nodeplugin-nfsplugin-tc26l      2/2     Running   0          6d4h
csi-provisioner-s3-0                1/1     Running   0          6d4h
csi-s3-jgpvw                        2/2     Running   0          6d4h
csi-s3-ktjb2                        2/2     Running   0          6d4h
dataset-operator-797d8c88f4-vvrlj   1/1     Running   0          6d4h

**Comment by YiannisGkoufas** [comment]
Ok! Can you share the logs of `csi-s3-jgpvw` and `csi-s3-ktjb2` pods?

**Comment by HelenCousins** [comment]
kubectl logs -n dlf csi-s3-jgpvw driver-registrar 
I0319 10:08:45.794651       1 main.go:110] Version: v1.2.0-0-g6ef000ae
I0319 10:08:45.794707       1 main.go:120] Attempting to open a gRPC connection with: "/csi/csi.sock"
I0319 10:08:45.794722       1 connection.go:151] Connecting to unix:///csi/csi.sock
W0319 10:08:55.794897       1 connection.go:170] Still connecting to unix:///csi/csi.sock
W0319 10:09:05.794859       1 connection.go:170] Still connecting to unix:///csi/csi.sock
I0319 10:09:10.223604       1 main.go:127] Calling CSI driver to discover driver name
I0319 10:09:10.223661       1 connection.go:180] GRPC call: /csi.v1.Identity/GetPluginInfo
I0319 10:09:10.223666       1 connection.go:181] GRPC request: {}
I0319 10:09:10.227437       1 connection.go:183] GRPC response: {"name":"ch.ctrox.csi.s3-driver","vendor_version":"v1.1.1"}
I0319 10:09:10.227937       1 connection.go:184] GRPC error: <nil>
I0319 10:09:10.227944       1 main.go:137] CSI driver name: "ch.ctrox.csi.s3-driver"
I0319 10:09:10.227973       1 node_register.go:58] Starting Registration Server at: /registration/ch.ctrox.csi.s3-driver-reg.sock
I0319 10:09:10.228235       1 node_register.go:67] Registration Server started at: /registration/ch.ctrox.csi.s3-driver-reg.sock
I0319 10:09:10.418472       1 main.go:77] Received GetInfo call: &InfoRequest{}
I0319 10:09:10.438809       1 main.go:87] Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:true,Error:,}
kubectl logs -n dlf csi-s3-jgpvw csi-s3 
I0319 10:09:09.290984       1 s3-driver.go:80] Driver: ch.ctrox.csi.s3-driver 
I0319 10:09:09.291100       1 s3-driver.go:81] Version: v1.1.1 
I0319 10:09:09.291129       1 driver.go:81] Enabling controller service capability: CREATE_DELETE_VOLUME
I0319 10:09:09.291142       1 driver.go:93] Enabling volume access mode: SINGLE_NODE_WRITER
I0319 10:09:09.291612       1 server.go:108] Listening for connections on address: &net.UnixAddr{Name:"//csi/csi.sock", Net:"unix"}
I0319 10:09:10.225493       1 utils.go:97] GRPC call: /csi.v1.Identity/GetPluginInfo
I0319 10:09:10.225513       1 utils.go:98] GRPC request: {}
I0319 10:09:10.226576       1 identityserver-default.go:32] Using default GetPluginInfo
I0319 10:09:10.226584       1 utils.go:103] GRPC response: {"name":"ch.ctrox.csi.s3-driver","vendor_version":"v1.1.1"}
I0319 10:09:10.419737       1 utils.go:97] GRPC call: /csi.v1.Node/NodeGetInfo
I0319 10:09:10.419761       1 utils.go:98] GRPC request: {}
I0319 10:09:10.420309       1 nodeserver-default.go:40] Using default NodeGetInfo
I0319 10:09:10.420314       1 utils.go:103] GRPC response: {"node_id":"hc7testlus-worker-new-1"}

kubectl logs -n dlf csi-s3-ktjb2 driver-registrar 
I0319 10:08:45.887209       1 main.go:110] Version: v1.2.0-0-g6ef000ae
I0319 10:08:45.887248       1 main.go:120] Attempting to open a gRPC connection with: "/csi/csi.sock"
I0319 10:08:45.887261       1 connection.go:151] Connecting to unix:///csi/csi.sock
W0319 10:08:55.887457       1 connection.go:170] Still connecting to unix:///csi/csi.sock
W0319 10:09:05.887421       1 connection.go:170] Still connecting to unix:///csi/csi.sock
I0319 10:09:10.316125       1 main.go:127] Calling CSI driver to discover driver name
I0319 10:09:10.316149       1 connection.go:180] GRPC call: /csi.v1.Identity/GetPluginInfo
I0319 10:09:10.316168       1 connection.go:181] GRPC request: {}
I0319 10:09:10.319191       1 connection.go:183] GRPC response: {"name":"ch.ctrox.csi.s3-driver","vendor_version":"v1.1.1"}
I0319 10:09:10.319760       1 connection.go:184] GRPC error: <nil>
I0319 10:09:10.319768       1 main.go:137] CSI driver name: "ch.ctrox.csi.s3-driver"
I0319 10:09:10.319987       1 node_register.go:58] Starting Registration Server at: /registration/ch.ctrox.csi.s3-driver-reg.sock
I0319 10:09:10.320321       1 node_register.go:67] Registration Server started at: /registration/ch.ctrox.csi.s3-driver-reg.sock
I0319 10:09:10.360591       1 main.go:77] Received GetInfo call: &InfoRequest{}
I0319 10:09:10.381424       1 main.go:87] Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:true,Error:,}
ubectl logs -n dlf csi-s3-ktjb2 csi-s3 
sudo mount -t cifs -o credentials=/home/jovyan/.smbcredentials //netapp1b/ /home/jovyan/my-home-dir/   -o vers=1.0

kubectl logs -n dlf csi-s3-ktjb2 csi-s3 
...
long
...
I0325 15:58:33.966529       1 utils.go:98] GRPC request: {"capacity_range":{"required_bytes":5368709120},"name":"pvc-4455b38c-b97b-4839-b025-66e091de759c","parameters":{"mounter":"goofys"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{}},"access_mode":{"mode":5}}]}
I0325 15:58:33.968280       1 controllerserver.go:67] Got a request to create volume pvc-4455b38c-b97b-4839-b025-66e091de759c
E0325 15:58:33.968329       1 utils.go:101] GRPC error: failed to initialize S3 client: Endpoint:  does not follow ip address or domain name standards.
I0325 16:03:33.973106       1 utils.go:97] GRPC call: /csi.v1.Controller/CreateVolume
I0325 16:03:33.973166       1 utils.go:98] GRPC request: {"capacity_range":{"required_bytes":5368709120},"name":"pvc-4455b38c-b97b-4839-b025-66e091de759c","parameters":{"mounter":"goofys"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{}},"access_mode":{"mode":5}}]}
I0325 16:03:33.975720       1 controllerserver.go:67] Got a request to create volume pvc-4455b38c-b97b-4839-b025-66e091de759c
E0325 16:03:33.975768       1 utils.go:101] GRPC error: failed to initialize S3 client: Endpoint:  does not follow ip address or domain name standards.

**Comment by YiannisGkoufas** [comment]
Can you confirm one more thing? Did you edit the `endpoint` field of the existing Dataset or you deleted and created a new one?

**Comment by HelenCousins** [comment]
I edited it.

**Comment by YiannisGkoufas** [comment]
Ah okay, its not supported yet (apologies that is not stated anywhere in the documentation)
Is it possible to try deleting and recreating the Dataset?

**Comment by HelenCousins** [comment]
oh, yes, I will try that

**Comment by HelenCousins** [comment]
oh wow, I have a pvc! thank you so much! (er, now to test it has my objects in it)

**Comment by HelenCousins** [comment]
oh great, I made a pod with ubuntu and told it to mount my pvc...
MountVolume.SetUp failed for volume "pvc-53d7eb9b-2701-4220-865b-f4e8955d1978" : rpc error: code = Unknown desc = Error fuseMount command: goofys args: [--endpoint=https://s3.amazonaws.com --profile=pvc-53d7eb9b-2701-4220-865b-f4e8955d1978 --type-cache-ttl 1s --stat-cache-ttl 1s --dir-mode 0777 --file-mode 0777 --http-timeout 5m -o allow_other --region eu-west-2 atestbuckethc7 /var/lib/kubelet/pods/f17dcc61-55eb-4829-8b7a-b250985d7541/volumes/kubernetes.io~csi/pvc-53d7eb9b-2701-4220-865b-f4e8955d1978/mount] output: 2021/03/26 16:01:25.259621 main.FATAL Unable to mount file system, see syslog for details

**Comment by YiannisGkoufas** [comment]
I see, have you tried to mount the bucket locally with s3fs?

**Comment by HelenCousins** [comment]
I hadn't.  Now I have, it worked

**Comment by YiannisGkoufas** [comment]
Would it be possible to share the command you used? without the credentials file.

**Comment by HelenCousins** [comment]
s3fs atestbuckethc7 folder -o passwd_file=${HOME}/.passwd-s3fs

(my objects are in 'folder' now; the credentials are the same as the json file for the dataset)

**Comment by HelenCousins** [comment]
it should be an entirely public bucket btw, it contains a picture.

**Comment by YiannisGkoufas** [comment]
Hi @HelenCousins I figured out the correct format. Can I ask that you delete and create a new dataset (one final time!) using that spec:
```
apiVersion: com.ie.ibm.hpsys/v1alpha1
kind: Dataset
metadata:
  name: mybucket-yiannis
spec:
  local:
    type: "COS"
    accessKeyID: "XXXXXXXXXX"
    secretAccessKey: "XXXXXXXXXXXXXXXXx"
    endpoint: "http://s3.eu-west-2.amazonaws.com"
    bucket: "atestbuckethc7"
```
Notice that I removed the `region` section and the change that I made in the `endpoint`.
Also make sure that you first delete the pod that tried to mount the old dataset.
Please let me know if this works.

**Comment by YiannisGkoufas** [comment]
Hi @HelenCousins is it working as expected?

**Comment by HelenCousins** [comment]
appologies I had a vacation (in my lounge...) yes, it does now work, wow, this is very clever, and I can put my bucket contents into a daft web page.  thank you.

**Comment by YiannisGkoufas** [comment]
Great news! Thanks for your feedback!
