### ISSUE TITLE
Dataset Operator permission mismatch

### ISSUE THREAD

**Issue by viktoriaas** [datashim-io/datashim#96]
Hi, 

I have cluster with pod security policy enabled. When I try to deploy operator I always get `Error: container has runAsNonRoot and image will run as root` in dataset-operator Deployment.

The issue is resolved with adding security context under `spec.template.spec`. I used 
```    
spec:
      securityContext:
        runAsUser: 1000
```
and pod starts now.

Could similar fix be added to the code?

**Comment by YiannisGkoufas** [comment]
Hi @viktoriaas what kubernetes version are you deploying to?

**Comment by viktoriaas** [comment]
@YiannisGkoufas 
it's version v1.20.5 deployed with rke2r1
